# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notifbuddy < Formula
  desc "Two-way Linear <-> Slack sync, from your terminal"
  homepage "https://notifbuddy.com"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.14.0/notifbuddy_0.14.0_darwin_amd64.tar.gz"
      sha256 "5ea06b59b50ff1f0c9f35ca887f651e37cc4e081541fad13b0435b2954c4f923"

      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.14.0/notifbuddy_0.14.0_darwin_arm64.tar.gz"
      sha256 "7ae0b918782e2340872a48c862947552e4cd06088d0fc5a17f2f504fc4994922"

      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.14.0/notifbuddy_0.14.0_linux_amd64.tar.gz"
      sha256 "447731946cd016bc94368426b897a50b2e277fb695f996b5bc95506113b4f85d"
      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.14.0/notifbuddy_0.14.0_linux_arm64.tar.gz"
      sha256 "e1c95c2eb8baadbdf87433a3a3d28a33b3e97ff653e7892ea28ee5fd5cb55d7a"
      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
  end

  def caveats
    <<~EOS
      Sign in with:
        notifbuddy login

      Let Claude (or another coding agent) run your onboarding:
        notifbuddy skill install
      then ask the agent to "set up notifbuddy".
    EOS
  end

  test do
    system "#{bin}/notifbuddy", "--version"
  end
end
