# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notifbuddy < Formula
  desc "Two-way Linear <-> Slack sync, from your terminal"
  homepage "https://notifbuddy.com"
  version "0.20.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.20.1/notifbuddy_0.20.1_darwin_amd64.tar.gz"
      sha256 "574a466128e930b51318a1265091e391423e4bd51339058e49a82d15c9aa9075"

      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.20.1/notifbuddy_0.20.1_darwin_arm64.tar.gz"
      sha256 "f85eb69c087bb0c671bd53d6a63a8e5622b7aa306c41a168c187f01dfa813428"

      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.20.1/notifbuddy_0.20.1_linux_amd64.tar.gz"
      sha256 "b6c0e14bd9b13a5f95277c5b2c79e03df03e4f3b6e5ae6048e8389215458b1d1"
      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notifbuddy/notifbuddy/releases/download/v0.20.1/notifbuddy_0.20.1_linux_arm64.tar.gz"
      sha256 "6de2c24d36e5cc6bd766c6a2120e7a03bd6f203faab938ee4e3bd47d6fca858f"
      define_method(:install) do
        bin.install "notifbuddy"
      end
    end
  end

  def caveats
    <<~EOS
      Sign in with:
        notifbuddy login

      Let Claude (or another coding agent) run your onboarding:
        notifbuddy skill install
      then ask the agent to "set up notifbuddy".
    EOS
  end

  test do
    system "#{bin}/notifbuddy", "--version"
  end
end
